# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '10.0'

target 'KeyFrames' do
    use_frameworks!
    pod 'GroundSdk'
    pod 'ArsdkEngine'
    pod 'SdkCore'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'


  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

end
